In [1]:
import numpy as np

In [38]:
def im2col(input_data, filter_h, filter_w, stride=1, pad=0):
    H, W = input_data.shape
    out_h = (H + 2*pad - filter_h)//stride + 1
    out_w = (W + 2*pad - filter_w)//stride + 1

    img = np.pad(input_data, [ (pad, pad), (pad, pad)], 'constant')
    col = np.zeros((filter_h, filter_w, out_h, out_w))

    for y in range(filter_h):
        y_max = y + stride*out_h
        for x in range(filter_w):
            x_max = x + stride*out_w
            col[ y, x, :, :] = img[ y:y_max:stride, x:x_max:stride]
    col = col.transpose( 2, 3, 0, 1).reshape( out_h*out_w, -1)

    return col

def convolution(X, Y, padding = 0, stride = 1):
    H, W = X.shape
    FH, FW = Y.shape
    out_h = 1 + int((H + 2*padding - FH) / stride)
    out_w = 1 + int((W + 2*padding - FW) / stride)

    col = im2col(X, FH, FW, stride, padding)
    col_W = Y.reshape(1, -1).T

    out = np.dot(col, col_W)
    out = out.reshape(out_h, out_w)

    return out

In [42]:
X = np.array([
    [1,2,3,0],
    [0,1,2,3],
    [3,0,1,2],
    [2,3,0,1]
])

Y = np.array([
    [2,0,1],
    [0,1,2],
    [1,0,2]
])

print(convolution(X, Y))

[[15. 16.]
 [ 6. 15.]]


In [41]:
print(convolution(X, Y, padding=1))

[[ 7. 12. 10.  2.]
 [ 4. 15. 16. 10.]
 [10.  6. 15.  6.]
 [ 8. 10.  4.  3.]]


In [44]:
Z= np.array([
  [1,2,3,0,1,2,3],
  [0,1,2,3,0,1,2],
  [3,0,1,2,3,0,1],
  [2,3,0,1,2,3,0],
  [1,2,3,0,1,2,3],
  [0,1,2,3,0,1,2],
  [3,0,1,2,3,0,1]
])

print(convolution(Z, Y, padding=0, stride=2))

[[15. 17. 15.]
 [17. 15. 17.]
 [15. 17. 15.]]
