# 畳み込み
## 2次元畳み込みから3次元畳み込みへ

In [15]:
import numpy as np

In [25]:
def conv2d(A, B):
    """二次元配列A, Bの畳み込みを計算する
    - `scipy.signal.convolve2d`とは異なる実装なので注意が必要
    """
    n = A.shape[0] # 配列Aの次元
    m = B.shape[0] # 配列Bの次元
    k = min(n, m) # 配列Aと配列Bの小さい方の次元
    t = abs(n - m) + 1 # 戻り値の配列の次元

    C = np.zeros((t, t))

    for i in range(t):
        for j in range(t):
            a = A[i:i+k, j:j+k].flatten()
            b = B.flatten()
            C[i, j] = np.dot(a, b)
            
    return C

In [26]:
A1 = np.array(
    [[5, 0, 1],
     [1, 3, 1],
     [2, 4, 0]]
)

A2 = np.array(
    [[7, 3, 1],
     [5, 1, 2],
     [0, 4, 0]]
)

A3 = np.array(
    [[2, 1, 0],
     [1, 0, 2],
     [4, 7, 6]]
)

In [27]:
B1 = np.array(
    [[1, 3],
     [0, 1]]
)

B2 = np.array(
    [[1, 3],
     [0, 2]]
)

B3 = np.array(
    [[2, 1],
     [0, 3]]
)

In [28]:
C1 = conv2d(A1, B1)
C2 = conv2d(A2, B2)
C3 = conv2d(A3, B3)

In [29]:
display(C1)
display(C2)
display(C3)

array([[ 8.,  4.],
       [14.,  6.]])

array([[18., 10.],
       [16.,  7.]])

array([[ 5.,  8.],
       [23., 20.]])

In [32]:
OUT = C1 + C2 + C3
OUT

array([[31., 22.],
       [53., 33.]])